import { useEffect } from 'react'
import Head from 'next/head'
import { useDispatch } from 'react-redux'
import sistemasActions from '../store/actions/sistemasActions'
import Title from '../components/Title'

export default function Home() {

  // const redux = useSelector(state => state)
  const dispatch = useDispatch()
  
  useEffect(() => {
    dispatch(sistemasActions.edit_mode_sistemas(true))
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          <Title/>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>

      <footer>
       
      </footer>
    </div>
  )
}
